services:
  php:
    build:
      context: docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

  composer:
    image: composer:latest
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - symfony

networks:
  symfony:

volumes:
  db_data:
